### ISSUE TITLE
wiki firebase site-adapter?

### ISSUE THREAD

**Issue by cliveb** [fedwiki/wiki-plugin-assets#8]
Last weeks weekly wiki meeting discussed was Firebase hosting. Paul would need to write a "[site-adapter for Firebase". 
](http://clive.tries.fed.wiki/view/wiki-devuser-video-chat-dec-5)

I'm very interested in deploying to Firebase, because with typical traffic hosting is free. I searched for dev doc on witting a site-adapter, is [assets.coffee ]( https://github.com/WardCunningham/wiki-plugin-assets/blob/master/client/assets.coffee)code that I can use as a template. All direction and pointers appreciated.

**Comment by WardCunningham** [comment]
Here is the site adapter that talks over http/https to servers.
https://github.com/fedwiki/wiki-client/blob/master/lib/siteAdapter.coffee

There is a lot of complication detecting and then saving the required protocol and proxy services to grandfather in http protocol. Don't expect a tutorial.

I suspect you could pay for years of digital ocean hosting for the time it would take to debug a firebase adapter. But then the learning could be useful.
